title: "Critical Editions"
subtitle: "Holocaust Testimonies in Historical Context"
introCopy: "The Critical Editions Series contextualizes Fortunoff Video testimonies in their historical time and place. Each testimony in the series was chosen by one of our visiting scholars. Each scholar then produced an introductory essay about the chosen testimony, along with an annotated transcript that provides additional insight and background information."
homeLink: "https://fortunoff.library.yale.edu"
callToAction: true
impactImageCaption: "Photo: Steven H. and Marion L. Holocaust testimony (HVT-544), recorded in 1985."
organizationName: "Fortunoff Video Archive for Holocaust Testimonies"
parentOrganizationName: "Yale University"
parentOrganizationURL: "https://library.yale.edu"
showBylinesOnIndexPage: true
showSupertitlesOnIndexPage: false
textOnlyIndexPage: false
essayOrder:
  - hvt-3164
  - hvt-2348
  - hvt-2033
  - hvt-0170
  - hvt-0574
  - hvt-3280
  - hvt-0536
  - hvt-3038
  - hvt-3171
  - hvt-0764
  - hvt-0237
  - hvt-3169
  - hvt-8008	
  
  
  
  
  
  
