name: Deploy to S3 Staging

on:
  workflow_dispatch: {}
  push:
    branches:
      - staging

env:
  AWS_REGION: ca-central-1
  S3BUCKET: critical-editions-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ AWS_REGION }}
      - name: Deploy data to S3 bucket
        run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          aws s3 sync ./data s3://${{ env.S3BUCKET }}/data
